version: '3'

services:
  solr:
    image: solr
    container_name: solr
    environment:
      - SOLR_HOME=/var/solr/data
    ports:
      - "8983:8983"
    volumes:
      - ./solr-config/movies:/opt/solr/server/movies-config
    command:
      - bash
      - -c
      - |
        precreate-core movies /opt/solr/server/movies-config;  exec solr -f


# finaly
#       - bash
#       - -c
#       - |
#         precreate-core movies; exec solr -f

  
      # - |
      #   /opt/solr/bin/solr start -f -force &&
      #   sleep 2 &&
      #   /opt/solr/bin/solr sorl-precreate movies
